# NumPy Çalışma

### NumPy Array'i Oluşturmak

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.4'

In [55]:
# code here
np.arange(1, 6)

array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [6]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [7]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [8]:
np.array([3.14, 4, 2, 13], dtype = "float")

array([ 3.14,  4.  ,  2.  , 13.  ])

In [18]:
# sifirdan array olusturma (np.zeros)

In [10]:
# code here
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# code here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# birlerden array olusturma (np.ones)

In [20]:
# code here
np.ones((3, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
# code here
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# belirlenen değerler ile doldurma (np.full)

In [23]:
# code here
np.full((3,5),3, dtype="float")

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [24]:
# code here (arange)
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [27]:
# code here (linspace)
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [36]:
# code here (random.normal)
np.random.normal(13,17, size=(3,4))

array([[ 19.6130502 ,  23.76490944,  20.24633855,   3.12147343],
       [-15.39280113,  27.39490847,  -7.15731653,   1.23709797],
       [ -2.17578089,  20.57606068,  42.70846694,  -4.60836427]])

array([[17.36153175, 13.13320486,  7.9751651 , 10.96652924],
       [15.88966379, 14.9596121 ,  0.79541802, 13.03982467],
       [11.16320473,  8.95138261, 11.24850164, 14.35247169]])

In [41]:
# code here (random.randint)
np.random.randint(5,8, size = (5,2))

array([[6, 7],
       [5, 6],
       [5, 7],
       [6, 5],
       [6, 5]])

array([[5, 8],
       [5, 2],
       [7, 5],
       [7, 7],
       [0, 5]])

### Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [3]:
import numpy as np

In [44]:
# code here(random.randint, hihg=10, size=10)
np.random.randint(1,9, size = 10)

array([7, 4, 5, 3, 1, 5, 6, 1, 2, 1])

array([9, 8, 7, 8, 5, 3, 6, 8, 2, 8])

In [25]:
a = np.random.randint(10, size = 10)
a

array([7, 0, 9, 2, 7, 7, 6, 6, 9, 1])

In [26]:
# code here (find the dimension of a)
a[-1]

1

1

In [27]:
# code here (find the shape of a)
a.shape

(10,)

(10,)

In [31]:
# code here (find the size of a)


10

In [36]:
# code here (find the dtype of a)
a.dtype

dtype('int32')

dtype('int32')

In [39]:
# code here(assign your code to 'b', random.randint, hihg=20, size=(4,6))
b=np.random.randint(1,20,size=(4,6))
b

array([[18, 19, 19,  1,  4, 17],
       [ 2,  6,  5,  7, 15, 16],
       [ 9, 18, 14, 17, 12, 11],
       [16, 12,  9, 15,  2, 11]])

In [40]:
b

array([[18, 19, 19,  1,  4, 17],
       [ 2,  6,  5,  7, 15, 16],
       [ 9, 18, 14, 17, 12, 11],
       [16, 12,  9, 15,  2, 11]])

In [51]:
b = np.random.randint(20, size = (4,6))

In [43]:
# code here (find the dimension of b)
b.ndim

2

2

In [44]:
# code here (find the shape of b)
b.shape

(4, 6)

(4, 6)

In [45]:
# code here (find the size of b)
b.size

24

24

In [46]:
# code here (find the dtype of b)
b.dtype

dtype('int32')

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [47]:
import numpy as np

In [49]:
# code here (arange, start=1, stop=10)
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# code here (reshape (3,3) your coding above)
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a = np.arange(1,10)

In [58]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# code here (find the dimension of a)
a.ndim

1

1

In [98]:
# code here (reshape a as (1,9) and assign to b)
b = a.reshape(1,2)
b

array([[1, 2]])

In [159]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [93]:
# code here (find the dimension of b)
b.ndim

2

2

### Array Birlestirme (Concatenation)

In [94]:
import numpy as np

In [95]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [99]:
# code here (concatenate x and y)
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [100]:
z = np.array([7,8,9])

In [101]:
# code here (concatenate x, y and z)
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
# code here (concatenate z, y and x)
np.concatenate([z,y,x])

array([7, 8, 9, 4, 5, 6, 1, 2, 3])

array([7, 8, 9, 4, 5, 6, 1, 2, 3])

In [103]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [105]:
# code here (concatenate a and a)
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [106]:
# code here (concatenate a and a)
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [107]:
import numpy as np

In [108]:
x = np.array([1,2,3,99,99,3,2,1])

In [110]:
# code here (split x from 3 and 5)
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [111]:
# code here (do a tuple unpacking for above splitting in order of a,b,c)
a,b,c=np.split(x, [3,5])

In [112]:
a

array([1, 2, 3])

In [113]:
b

array([99, 99])

In [114]:
c

array([3, 2, 1])

In [178]:
#iki boyutlu ayırma

In [115]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
# code here (split m)
np.split(m, [1,3], axis=0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [119]:
# code here (split m)
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### Array Sıralama (Sorting)

In [120]:
import numpy as np

In [121]:
v = np.array([2,1,4,3,5])

In [122]:
v

array([2, 1, 4, 3, 5])

In [123]:
# code here (sort v)
np.sort(v)

array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [196]:
# iki boyutlu array siralama

In [128]:
m = np.random.normal(20,5, (3,3))

In [129]:
np.sort(m, axis=0)

array([[19.58653751, 14.21914144, 17.42092724],
       [19.93654606, 14.91921739, 19.31369396],
       [27.39579229, 30.89072573, 28.24483103]])

array([[19.38973196, 24.03838428, 21.711276  ],
       [21.31152546, 12.27819458, 15.3705555 ],
       [13.03424857, 13.36797511, 20.6720354 ]])

In [130]:
# code here (sort m)
np.sort(m, axis=1)

array([[14.21914144, 19.58653751, 28.24483103],
       [14.91921739, 17.42092724, 19.93654606],
       [19.31369396, 27.39579229, 30.89072573]])

array([[11.4711052 , 20.00086064, 28.44452052],
       [15.02090679, 16.0648143 , 23.22445351],
       [ 9.34939833, 20.03722184, 22.39429448]])

In [131]:
# code here (sort m)
np.sort(m, axis=0)

array([[19.58653751, 14.21914144, 17.42092724],
       [19.93654606, 14.91921739, 19.31369396],
       [27.39579229, 30.89072573, 28.24483103]])

array([[16.0648143 , 11.4711052 ,  9.34939833],
       [20.00086064, 22.39429448, 15.02090679],
       [20.03722184, 23.22445351, 28.44452052]])

# Index ile Elemanlara Erişmek

In [132]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([9, 5, 7, 8, 1, 7, 3, 7, 4, 6])

In [134]:
# code here
a[6]

3

3

In [135]:
# code here
a[-1]

6

6

In [136]:
a[2], a[5], a[9] = [4, 0, 100]

In [137]:
# code here
a[2]

4

4

In [138]:
# code here
a[5]

0

0

In [139]:
# code here
a[9]

100

100

In [142]:
m = np.random.randint(10, size = (3,5))
m

array([[6, 7, 9, 1, 8],
       [7, 4, 8, 1, 1],
       [7, 0, 4, 5, 0]])

In [143]:
# code here
m[0,4]

8

8

In [144]:
# code here
m[0,0]

6

6

In [145]:
# code here
m[0, 2]

9

9

In [85]:
# code here (look at the below array)

In [146]:
m

array([[6, 7, 9, 1, 8],
       [7, 4, 8, 1, 1],
       [7, 0, 4, 5, 0]])

In [147]:
# code here
m[2, 3]

5

In [87]:
m[2, 3]

3

In [88]:
# code here (look at the below array)

In [89]:
m

array([[  8,   4,   2,   4,   6],
       [  5,   6,   4,   2,  99],
       [  8,   0,   0, 111,   6]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [1]:
import numpy as np

In [148]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [150]:
# code here
a[0:3]

array([20, 21, 22])

array([20, 21, 22])

In [151]:
# code here
a[0:3]

array([20, 21, 22])

array([20, 21, 22])

In [153]:
# code here
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

array([23, 24, 25, 26, 27, 28, 29])

In [155]:
# code here
a[1::2]

array([21, 23, 25, 27, 29])

array([21, 23, 25, 27, 29])

In [156]:
# code here
a[0::2]

array([20, 22, 24, 26, 28])

array([20, 22, 24, 26, 28])

In [157]:
# code here
a[2::2]

array([22, 24, 26, 28])

array([22, 24, 26, 28])

In [158]:
# code here
a[::3]

array([20, 23, 26, 29])

array([20, 23, 26, 29])

In [224]:
#iki boyutlu slice islemleri

In [161]:
m = np.random.randint(10, size = (5,5))

In [162]:
m

array([[7, 2, 5, 5, 8],
       [0, 2, 3, 2, 9],
       [6, 3, 9, 8, 3],
       [2, 7, 7, 4, 8],
       [5, 6, 2, 3, 7]])

In [167]:
# code here
m[0:1,0:5]

array([[7, 2, 5, 5, 8]])

array([2, 4, 5, 3, 6])

In [168]:
# code here
m[1:2,:5]

array([[0, 2, 3, 2, 9]])

array([1, 3, 9, 1, 0])

In [169]:
# code here
m[3:4,0:5]

array([[2, 7, 7, 4, 8]])

array([8, 5, 3, 4, 0])

In [100]:
m

array([[2, 1, 8, 3, 8],
       [4, 3, 2, 3, 5],
       [5, 9, 3, 1, 3],
       [3, 1, 6, 9, 4],
       [6, 0, 9, 9, 0]])

In [170]:
# code here
m[0:1,0:5]

array([[7, 2, 5, 5, 8]])

array([2, 1, 8, 3, 8])

In [171]:
# code here
m[0:1,0:5]

array([[7, 2, 5, 5, 8]])

array([2, 1, 8, 3, 8])

In [172]:
# code here
m[1:2,:5]

array([[0, 2, 3, 2, 9]])

array([4, 3, 2, 3, 5])

In [175]:
# code here
m[0:2,:3]

array([[7, 2, 5],
       [0, 2, 3]])

array([[2, 1, 8],
       [4, 3, 2]])

In [177]:
# code here
m[0:5,:2]

array([[7, 2],
       [0, 2],
       [6, 3],
       [2, 7],
       [5, 6]])

array([[2, 1],
       [4, 3],
       [5, 9],
       [3, 1],
       [6, 0]])

In [107]:
m

array([[2, 1, 8, 3, 8],
       [4, 3, 2, 3, 5],
       [5, 9, 3, 1, 3],
       [3, 1, 6, 9, 4],
       [6, 0, 9, 9, 0]])

In [180]:
# code here
m[1:3,:2]

array([[0, 2],
       [6, 3]])

array([[4, 3],
       [5, 9]])

# Alt Küme Üzerinde İşlem Yapmak

In [181]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[9, 0, 0, 9, 2],
       [8, 7, 1, 7, 6],
       [3, 3, 5, 2, 8],
       [1, 3, 1, 1, 5],
       [1, 0, 6, 0, 9]])

array([[3, 5, 0, 7, 2],
       [8, 5, 4, 6, 1],
       [9, 0, 5, 9, 5],
       [7, 6, 6, 6, 3],
       [4, 3, 8, 7, 6]])

In [183]:
# code here
a[0:3,:2]

array([[9, 0],
       [8, 7],
       [3, 3]])

array([[3, 5],
       [8, 5],
       [9, 0]])

In [240]:
# code here

array([[99999,     5],
       [    8,   888],
       [    9,     0]])

In [114]:
a

array([[99999,     5,     0,     7,     2],
       [    8,   888,     4,     6,     1],
       [    9,     0,     5,     9,     5],
       [    7,     6,     6,     6,     3],
       [    4,     3,     8,     7,     6]])

In [3]:
m = np.random.randint(10, size = (5, 5))
m

array([[8, 1, 4, 0, 2],
       [4, 0, 3, 0, 6],
       [4, 1, 4, 0, 3],
       [1, 8, 0, 8, 9],
       [6, 0, 1, 2, 4]])

In [186]:
# code here
m[1:4,:2]

array([[0, 2],
       [6, 3],
       [2, 7]])

array([[7, 0],
       [7, 5],
       [7, 4]])

In [245]:
# code here

array([[9999,    0],
       [   9,    3],
       [   5,    1]])

In [247]:
m

array([[9, 0, 0, 8, 9],
       [9, 3, 4, 1, 9],
       [5, 1, 2, 1, 5],
       [8, 2, 3, 8, 0],
       [5, 7, 6, 3, 8]])

# Fancy Index ile Elemanlara Erişmek

In [187]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [188]:
# code here
v[1]

3

3

In [189]:
# code here
v[3]

9

9

In [190]:
# code here
v[5]

15

15

In [192]:
# code here
v[1:6:2]

array([ 3,  9, 15])

[3, 9, 15]

In [193]:
al_getir = [1,3,5]

In [194]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [195]:
# code here
v[1:6:2]

array([ 3,  9, 15])

array([ 3,  9, 15])

In [256]:
#iki boyutta fancy

In [196]:
m = np.arange(9).reshape((3,3))

In [197]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [198]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [199]:
m[satir, sutun]

array([1, 5])

In [261]:
#basit index ile fancy index

In [200]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [201]:
m[0, [1,2]]

array([1, 2])

In [264]:
#slice ile fancy

In [202]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [203]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [204]:
v < 3

array([ True,  True, False, False, False])

In [205]:
v[v < 3]

array([1, 2])

In [206]:
# code here
v[v > 3]

array([4, 5])

In [269]:
v[v > 3]

array([4, 5])

In [207]:
# code here
v[v > 2]

array([3, 4, 5])

array([3, 4, 5])

In [208]:
# code here
v[v < 4]

array([1, 2, 3])

array([1, 2, 3])

In [210]:
# code here
v[v == 3]

array([3])

array([3])

In [214]:
# code here
v[v != 3]

array([1, 2, 4, 5])

array([1, 2, 4, 5])

In [215]:
v

array([1, 2, 3, 4, 5])

In [216]:
# code here
v*2

array([ 2,  4,  6,  8, 10])

array([ 2,  4,  6,  8, 10])

In [218]:
# code here
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [219]:
# code here
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel İşlemler

Bu bölüm bilgi ve tekrar maksatlı konulmuştur.

In [220]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [221]:
v - 1

array([0, 1, 2, 3, 4])

In [222]:
v * 5

array([ 5, 10, 15, 20, 25])

In [223]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [224]:
#ufunc

In [225]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [226]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [227]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [228]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [229]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [230]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [231]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [232]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [233]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [234]:
np.absolute(np.array([-3]))

array([3])

In [235]:
np.sin(360)

0.9589157234143065

In [236]:
np.cos(180)

-0.5984600690578581

In [237]:
v = np.array([1,2,3])

In [238]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [239]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [240]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [ ]:
?np

# İstatistiksel Hesaplamalar

In [242]:
v

array([1, 2, 3])

In [243]:
np.mean(v)

2.0

In [244]:
v.sum()

6

In [245]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [307]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [246]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [247]:
a

array([[5, 1],
       [1, 3]])

In [248]:
b

array([12, 10])

In [249]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])