In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [2]:
samples = np.random.normal(100,15,1000)
samples

array([ 82.56739601, 101.81941763,  91.30022144, 110.11529327,
       113.78505149,  72.1730853 , 111.05004919, 122.3064806 ,
        87.52462277, 114.66333883,  66.2087295 ,  72.25667795,
        66.03527711,  95.46300064, 101.30721182, 125.57309081,
       116.54236553,  87.12155829, 105.08905281,  93.21520243,
        81.33830383,  98.5398915 , 111.76070827,  95.15052999,
       114.31899015, 131.86618497, 111.28519076, 103.56287528,
        91.54421634, 125.4631483 ,  89.08974433,  86.28319447,
       110.93953988,  89.46432268,  93.45815835,  91.82449894,
       107.39712802, 107.96977244,  86.04378897,  94.64066918,
        88.64146669, 106.65708815,  99.80444548,  95.04451675,
       107.03592375,  96.95105254, 117.65324209,  92.22916334,
       101.17708768,  93.79764625, 109.68844235,  81.5197923 ,
        95.35384843,  92.06428586,  96.90595225,  80.46425589,
       105.61962452,  91.78584678, 111.34624647, 106.23654768,
        81.75897362, 105.4148606 , 108.34902446, 102.12

Compute the mean, median, and mode

In [3]:
mean =np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)
print(mean)
print(median)
print(mode)

100.20162496164203
100.02595335272879
ModeResult(mode=array([47.0440898]), count=array([1]))


Compute the min, max, Q1, Q3, and interquartile range

In [4]:
min = np.min(samples)
print(min)
max = np.max(samples)
print(max)
q1 = np.percentile(samples,25)
print(q1)
q3 = np.percentile(samples,75)
print(q3)
iqr= stats.iqr(samples)
print(iqr)

47.04408980371553
147.06168478189355
90.28763687799736
110.54088014914
20.253243271142637


Compute the variance and standard deviation

In [ ]:
variance = np.var(samples)
print(variance)
std_dev = np.std(samples)
print(std_dev)

Compute the skewness and kurtosis

In [5]:
skewness = stats.skew(samples)
print(skewness)
kurtosis = stats.kurtosis(samples)
print(kurtosis)

0.029229457973250387
0.1138219633151678


NumPy Correlation Calculation
Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use np.arange()

In [7]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use np.array() to create a second array y containing 10 arbitrary integers.

In [9]:
y = np.array([1,2,3,4,5,6,7,8,9,10])
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Once you have two arrays of the same length, you can compute the correlation coefficient between x and y

In [10]:
r = np.corrcoef(x, y)
r

array([[1., 1.],
       [1., 1.]])

Pandas Correlation Calculation
Run the code below

In [12]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method to calculate Pearson's r correlation.

In [13]:
r = pd.DataFrame([x,y])
r.corr(method="pearson")

0    1    2    3    4    5    6    7    8    9
0  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
1  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
2  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
3  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
5  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
6 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
7 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
8 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
9 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [14]:
rho = r.corr(method="spearman")
print(rho)

     0    1    2    3    4    5    6    7    8    9
0  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
1  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
2  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
3  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
5  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
6 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
7 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
8 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
9 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0


Seaborn Dataset Tips
Import Seaborn Library

In [15]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [18]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [17]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [19]:
stats.mode(tips)

ModeResult(mode=array([[13.42, 2.0, 'Male', 'No', 'Sat', 'Dinner', 2]], dtype=object), count=array([[  3,  33, 157, 151,  87, 176, 156]]))

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [20]:
tips.corr(method='pearson')

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000