___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 2</p><h1>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [6]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [7]:
arr[8]

8

In [8]:
arr[-3]

8

In [9]:
arr[2:5]

array([2, 3, 4])

In [10]:
arr[:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [12]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [14]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
arr_2d[1] # satırları getiri. 1. satır

array([20, 25, 30])

In [17]:
arr_2d[1][1]

25

In [19]:
arr_2d[1,1] # ikinci yöntem

25

In [20]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [21]:
arr_2d[2,1]=99

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 99, 45]])

In [24]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 99]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [23]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [26]:
v[[3,5,7]] # [] parantezi unutma hata verir.

array([ 9, 15, 21])

In [27]:
arr2d=np.zeros((10,10),dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
for i in range(len(arr2d)):
    arr2d[i] = i
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [30]:
arr2d[[2,4,6]] # satırları döndürür.

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

<h3>any_array[[row indices], [column indices]]</h3>

In [32]:
jj=np.arange(1,17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
jj[[1,2],[0,3]] # 1. satır 2. eleman, 2. satır 3. elemanını verir.

array([ 5, 12])

### Using ***basic index*** and ***fancy index*** together

In [37]:
jj[2,[2,3]] # 2 rakamını ikidindede kullanıyor. 2. satır 2. eleman, 2 satır 3.elemen

array([11, 12])

In [39]:
jj[[2,3],1] # yukardaki ile benzer 

array([10, 14])

### Using ***basic slicing*** and ***fancy index*** together

In [40]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
jj[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

# Selection on a Condition

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [43]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
arr[arr>4] # true olanların değerlerini döndürür.

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[(arr>3) & (arr<8)] # & veya demek böyle yazılması gerekiyor.

array([4, 5, 6, 7])

In [49]:
arr[arr!=4]

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

https://numpy.org/doc/stable/user/theory.broadcasting.html

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[:5] = 99 # ilk 5 değere atama yapıldı

In [54]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_slice = arr[5:]
arr_slice

array([ 6,  7,  8,  9, 10])

In [56]:
arr_slice[-2:]= 5

In [57]:
arr_slice

array([6, 7, 8, 5, 5])

In [58]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8,  5,  5])

In [82]:
arr_copy = arr.copy() # kopyalam yapıldı
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr_copy[2:6] = 0 kopya üzerinde değişiklik yapıldı
arr_copy

array([99, 99,  0,  0,  0,  0,  7,  8,  5,  5])

In [61]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8,  5,  5])

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [63]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [66]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
import warnings # hata alınca yazmasını engeller
warnings.filterwarnings('ignore')

In [70]:
arr / arr # 0 ile 0 bölünmesi için hata verirdi normalde yukarda çalıştırdığımız için vermedi

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [72]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [74]:
arr + 1 # elemnt element işlem yapıyor.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [77]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [78]:
np.tan(np.pi/4)

0.9999999999999999

In [79]:
np.pi

3.141592653589793

In [80]:
np.log(1000)

6.907755278982137

In [81]:
np.log10(100)

2.0

## Statistical Calculations

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``np.corrcoef(arr)`` | Returns correlation coefficient of array

In [83]:
v=np.array([1,1,2,2,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [84]:
np.mean(v)

2.142857142857143

In [86]:
v.mean()

2.142857142857143

In [87]:
np.median(v)

2.0

In [88]:
v.var()

0.6938775510204082

In [91]:
np.random.seed(42) # seed her çalıştırdığımızda aynı rakamları verir.
xarr = np.random.randn(3,3)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [94]:
np.corrcoef(xarr) # satır ve sütünlar arasındaki kolarasyonları veriyor.

array([[ 1.        ,  0.33500663, -0.29669929],
       [ 0.33500663,  1.        ,  0.80039247],
       [-0.29669929,  0.80039247,  1.        ]])

# The End of the Session - 2

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.