In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
b = np.arange(0,11,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.linspace(0,40,4)

array([ 0.        , 13.33333333, 26.66666667, 40.        ])

In [9]:
np.arange(0,41,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [38]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

In [12]:
np.arange(0,40,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [15]:
np.random.randint(1,10)

3

In [20]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[2:5]

array([2, 3, 4])

In [22]:
arr = np.arange(1,8)
arr[arr>4]

array([5, 6, 7])

In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [24]:
arr_2d[0,2]

15

In [25]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [27]:
arr_1 = np.array([4,9,16,25,36])
arr_1

array([ 4,  9, 16, 25, 36])

In [28]:
np.sqrt(arr_1)

array([2., 3., 4., 5., 6.])

In [29]:
np.max(arr_2)

6

In [30]:
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1-arr_2

array([1, 1, 1])

In [31]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [32]:
arr_2d[2,1]

40

In [33]:
arr_2d[:1,1:]

array([[10, 15]])

In [34]:
arr = np.arange(1,6)
arr[arr>3]

array([4, 5])

In [35]:
arr_1 = np.arange(0,10)
arr_2 = arr_1 * 3
np.max(arr_2)

27

In [36]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-arr_2

array([0., 0., 0., 0., 0.])

In [37]:
arr=np.arange(1,37)
arr.shape

(36,)