___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 4</p><h1>
    

# Data Frames

 - ### ``DataFrames`` are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [2]:
import numpy as np
import pandas as pd

 ## Creating a DataFrame using the ``list``s of data and columns

pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)

Two-dimensional, size-mutable, potentially heterogeneous ``tabular`` data.

In [3]:
data = [1, 3, 5, 7, 9, 18]
data

[1, 3, 5, 7, 9, 18]

In [4]:
pd.DataFrame(data = data)

0
0   1
1   3
2   5
3   7
4   9
5  18

In [5]:
pd.Series(data = data)

0     1
1     3
2     5
3     7
4     9
5    18
dtype: int64

In [6]:
pd.DataFrame(data = data, columns=["col_1"])

col_1
0      1
1      3
2      5
3      7
4      9
5     18

 ## Creating a DataFrame using a ``NumPy Arrays``

In [7]:
m = np.arange(1,24,2).reshape(3,4)
m

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [8]:
df=pd.DataFrame(data=m, columns=['var1','var2','var3','var4'])
df

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [9]:
df.head()

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [10]:
df.tail(1)

var1  var2  var3  var4
2    17    19    21    23

In [11]:
df.sample(2)

var1  var2  var3  var4
0     1     3     5     7
2    17    19    21    23

In [12]:
df.columns # kolon isimlerini yazdırır.

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [13]:
for i in df.columns:
    print(i)

var1
var2
var3
var4


In [14]:
for i in df.columns:
    print(df[i].sum())

27
33
39
45


In [15]:
df.columns=["new1", "new2", "new3", "new4"] # kaç sütün varsa o kadar yazmamız lazım.
df

new1  new2  new3  new4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [16]:
df.index=["a", "b", "c"] # kaç satır varsa o kadar yazmamız lazım.
df

new1  new2  new3  new4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [18]:
df.rename(columns = {"new1": "a", "new2": "b"})

a   b  new3  new4
a   1   3     5     7
b   9  11    13    15
c  17  19    21    23

In [19]:
df.rename(index = {"a" : 1, "b":2})

new1  new2  new3  new4
1     1     3     5     7
2     9    11    13    15
c    17    19    21    23

In [20]:
df

new1  new2  new3  new4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [21]:
df.shape

(3, 4)

In [22]:
df.shape[1] # sütün sayısı

4

In [23]:
df.ndim # boyut sayısı

2

In [24]:
df.size

12

In [25]:
len(df) # satır sayar

3

In [26]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [27]:
type(df)

pandas.core.frame.DataFrame

In [28]:
type(df.values)

numpy.ndarray

 ## Creating a DataFrame using a ``dict``

In [29]:
s1 = np.random.randint(2,10, size = 4)
s2 = np.random.randint(3,10, size = 4)
s3 = np.random.randint(4,15, size = 4)

In [30]:
s1

array([8, 8, 2, 7])

In [31]:
s2

array([4, 4, 9, 6])

In [32]:
s3

array([ 9,  4, 10, 11])

In [33]:
my_dict = {"var1":s1, "var2":s2, "var3":s3}
my_dict

{'var1': array([8, 8, 2, 7]),
 'var2': array([4, 4, 9, 6]),
 'var3': array([ 9,  4, 10, 11])}

In [35]:
df1 = pd.DataFrame(my_dict)
df1

var1  var2  var3
0     8     4     9
1     8     4     4
2     2     9    10
3     7     6    11

In [37]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [38]:
[i for i in df1.index]

[0, 1, 2, 3]

In [39]:
"var1" in df1

True

### Now, let's examine again the ***idexing, selection*** and ***slicing*** methods and several ***attributes*** using a different DataFrame

In [40]:
from numpy.random import randn

In [41]:
randn(5,4)

array([[ 3.08427901e-01, -2.46931341e-01, -3.20442559e-01,
         3.60918293e-01],
       [ 9.93306975e-02,  3.05841610e-01, -1.67636098e+00,
         1.20814400e+00],
       [ 3.88241167e-03, -1.58195592e+00,  8.67879148e-01,
        -4.43384483e-01],
       [ 5.10010755e-01,  4.04059734e-01, -2.61058014e-04,
         7.98278745e-01],
       [-1.13599591e+00,  1.66678287e+00,  1.27574017e-01,
        -1.49405677e+00]])

In [43]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [141]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [46]:
df3["W"] # series döndürdü tek prantez

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

#### DataFrame Columns are just Series

In [48]:
df3[["W"]] # iki prantezle datafarem döndürür.

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [51]:
type(df3[["W"]])

pandas.core.frame.DataFrame

In [52]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [54]:
df3[["W", "X"]] # iki prantez içi çe olması gerekir.

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [59]:
df3["W":"Y"] # row olarak düşünmeliyiz böyle bir kullanım yok

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [57]:
df3["A":"C"]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [60]:
df3["A":"C"]["W"]

A    2.706850
B    0.651118
C   -2.018168
Name: W, dtype: float64

In [61]:
df3["A":"C"][["W", "Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813

**Creating a new column:**

In [62]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [65]:
df3["new"] = df3["X"] * df3["Y"]
df3

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.570325
B  0.651118 -0.319318 -0.848077  0.605965  0.270806
C -2.018168  0.740122  0.528813 -0.589001  0.391387
D  0.188695 -0.758872 -0.933237  0.955057  0.708208
E  0.190794  1.978757  2.605967  0.683509  5.156577

In [66]:
df3["new2"] = [1,2,3,4,5]
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [70]:
df3.columns = [ "W","X","Y","Z","new", "new2",] # kolon isimleri değişti.
df3

In [73]:
df3 = df3[["new", "new2","W","X","Y","Z"]] # kolon sıralaması değiştirmak
df3

new  new2         W         X         Y         Z
A  0.570325     1  2.706850  0.628133  0.907969  0.503826
B  0.270806     2  0.651118 -0.319318 -0.848077  0.605965
C  0.391387     3 -2.018168  0.740122  0.528813 -0.589001
D  0.708208     4  0.188695 -0.758872 -0.933237  0.955057
E  5.156577     5  0.190794  1.978757  2.605967  0.683509

## [Removing Columns & Rows](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-drop.ipynb)

 ### Removing Columns

In [75]:
df3.drop("new2", axis=1) # axis=1 kolonlarda aramak için

new         W         X         Y         Z
A  0.570325  2.706850  0.628133  0.907969  0.503826
B  0.270806  0.651118 -0.319318 -0.848077  0.605965
C  0.391387 -2.018168  0.740122  0.528813 -0.589001
D  0.708208  0.188695 -0.758872 -0.933237  0.955057
E  5.156577  0.190794  1.978757  2.605967  0.683509

In [77]:
df3.drop(["new","new2"], axis=1) # birden fazla düşermek için liste halinde yazılacak.

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [79]:
df3.drop(columns=["new","new2"]) # colums yazılırsa axis gerek yok

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop(["new","new2"], axis=1, inplace=True) # değişiklği kalıcı yapmak için

In [86]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

 ### Removing rows

In [87]:
df3.drop("C", axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [88]:
df3.drop(index = ["B"])

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [92]:
df4 = df3.drop("C", axis=0) # değişikliği kalıcı olarak yapmış olduk. başka değişkene atadık.
df4

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [93]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Selecting Rows

### First, let's take a quick look at [`.loc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-loc.ipynb) | [`.iloc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-iloc.ipynb)

#### `.loc[]` → allows us to select data using **labels** (names) of rows (index) & columns

#### `.iloc[]` → allows us to select data using **index numbers** of rows (index) & columns. it's like classical indexing logic

In [94]:
m = np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [95]:
df4.loc[4]

var1    20
var2    36
var3    31
var4    11
Name: 4, dtype: int32

In [96]:
df4.loc[[4]]

var1  var2  var3  var4
4    20    36    31    11

In [97]:
df4.loc[2:5] # loc ibarelere göre yapar

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23

In [100]:
df4.iloc[2:5] # 5 i dahil etmedi. iloc index numaralarını göre yapar.

var1  var2  var3  var4
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11

In [101]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [103]:
df4.iloc[1:4] # arka planda indexleme gibi yapıyor.

var1  var2  var3  var4
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [104]:
df.loc["a":"d"]

new1  new2  new3  new4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [ ]:
#df4.loc[1:4] gives on error

In [106]:
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [105]:
df4.iloc[3,1]

30

In [107]:
df4.loc["d", "var2"]

30

In [109]:
df4.loc["d":"g", "var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int32

In [110]:
df4.loc["d":"g"]["var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int32

In [111]:
df4.loc["d":"g"][["var3"]] # datafarem için içiçe pranteze alınır.

var3
d    25
e    31
f     9
g    38

In [112]:
df4.loc["d":"g", ["var3"]] # datafarem

var3
d    25
e    31
f     9
g    38

In [113]:
df4.iloc[2:5,2]

c    12
d    25
e    31
Name: var3, dtype: int32

In [114]:
df4.iloc[2:5][["var3"]]

var3
c    12
d    25
e    31

#### Let's continue to examine `.loc[]` and `.iloc[]` using ``df3`` again

In [115]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [116]:
df3.loc["C"]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [117]:
df3.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [119]:
df3.loc[["C"]] # çift prantez datfareme olarak getirir.

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [121]:
df3.iloc[[2]] # çift prantez datfareme olarak getirir.

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

### Selecting subset of rows and columns

 - ### `.loc[[row labels|names], [column labels|names]]`

 - ### `.iloc[[row index numbers], [column index numbers]]`

In [122]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [123]:
df3.loc["C","Z"]

-0.5890005332865824

In [125]:
df3.loc[["C"],["Z"]] # datafarem olarak getirir.

Z
C -0.589001

In [128]:
df3.loc[["A", "C"], ["X","Z"]] # kesişimlerini verir.

X         Z
A  0.628133  0.503826
C  0.740122 -0.589001

In [129]:
df3.iloc[[0,2],[0,3]]

W         Z
A  2.706850  0.503826
C -2.018168 -0.589001

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [130]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [131]:
df3>2

W      X      Y      Z
A   True  False  False  False
B  False  False  False  False
C  False  False  False  False
D  False  False  False  False
E  False  False   True  False

In [133]:
df3[df3>2]

W   X         Y   Z
A  2.70685 NaN       NaN NaN
B      NaN NaN       NaN NaN
C      NaN NaN       NaN NaN
D      NaN NaN       NaN NaN
E      NaN NaN  2.605967 NaN

In [135]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [134]:
df3[df3["Z"]>0.5]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [136]:
df3[df3["Z"]>0.5]["X"]

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [139]:
df3[df3["Z"]>0.5][["X"]]

X
A  0.628133
B -0.319318
D -0.758872
E  1.978757

#### For two conditions you can use **|** → `or`,  **&** →  `and` with parenthesis:

In [142]:
df3[(df3['W']>0) & (df3['Y']<1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [143]:
df3[(df3['W']>0) & (df3['Y']<1)] = 0

In [144]:
df3

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

### Conditional selection using ``.loc[]`` and ``.iloc[]``

In [145]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [146]:
df3.loc[(df3.X>0), ["X", "Y"]]

X         Y
A  0.628133  0.907969
C  0.740122  0.528813
E  1.978757  2.605967

In [148]:
df3.loc[((df3.W>1) | (df3.Y<1)), ['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [149]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [151]:
df3.reset_index() # normal indexleri sütün haline getirip kendisi atama yaptı

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [153]:
df3.reset_index(drop = True) # eski indexi sildi.

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [155]:
df3.set_index("Z") # z yi direk indexe getirdi diğerini attı. kalıcı olması için inplace= True yapılır.

W         X         Y
Z                                      
 0.503826  2.706850  0.628133  0.907969
 0.605965  0.651118 -0.319318 -0.848077
-0.589001 -2.018168  0.740122  0.528813
 0.955057  0.188695 -0.758872 -0.933237
 0.683509  0.190794  1.978757  2.605967

In [158]:
df3.reset_index(drop =True, inplace=True) # yaptıgımız index değişti ve kalıcı oldu.

In [157]:
df3

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

### let's take a quick look at the [``.xs()``](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-xs.ipynb)

### Let's learn new functions/attributes/methods on "iris dataset" 

# End of the Session