___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import numpy as np
import pandas as pd

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [2]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [3]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [6]:
arr

array([10, 20, 30])

In [9]:
pd.Series(data=arr, index=labels) # indexlerini kendimiz yazabiliyoruz.

a    10
b    20
c    30
dtype: int32

### **Using Dictionary**

In [10]:
d

{'a': 10, 'b': 20, 'c': 30}

In [11]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [14]:
pd.Series(d, index=["q", "c", "y"]) # eger yazdığında indexte uazdığınlınla aynı olan indexleri getirir. diğerleri non getirir.
#  NON ların data typeleri floatdır.

q     NaN
c    30.0
y     NaN
dtype: float64

### Using Scalar Value

In [15]:
pd.Series("Faruk")

0    Faruk
dtype: object

In [17]:
pd.Series("Faruk", index =range(1,5)) # index sayısı kadar farukları çaoğaltır.

1    Faruk
2    Faruk
3    Faruk
4    Faruk
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [30]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [31]:
pd.Series([sum, print, len])[0]([3,5,7])

15

In [41]:
pd.Series([set, list, dict])[2]([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [32]:
mix_data = ['Aziz', 2, True]

In [34]:
ser = pd.Series(mix_data) # data type object verdi str var int var bool var
ser

0    Aziz
1       2
2    True
dtype: object

In [35]:
ser.dtype

dtype('O')

In [36]:
type(ser)

pandas.core.series.Series

In [37]:
type(ser[1])

int

In [38]:
arr = np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U11')

In [40]:
type(arr[2])

numpy.str_

### Basic Attributes of Series

In [43]:
ser = pd.Series(np.random.randint(0,100,7))
ser

0    59
1    67
2    97
3     9
4    67
5    24
6    71
dtype: int32

In [44]:
ser.dtype

dtype('int32')

In [45]:
type(ser)

pandas.core.series.Series

In [46]:
ser.shape

(7,)

In [48]:
ser.size

7

In [49]:
len(ser)

7

In [51]:
ser.ndim # boyut sayısı

1

In [52]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [53]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [54]:
for i in ser.index:
    print(i)


0
1
2
3
4
5
6


In [55]:
ser.keys

<bound method Series.keys of 0    59
1    67
2    97
3     9
4    67
5    24
6    71
dtype: int32>

In [56]:
ser.keys()

RangeIndex(start=0, stop=7, step=1)

In [58]:
ser.values # değerleri array olarak döndürür.

array([59, 67, 97,  9, 67, 24, 71])

In [61]:
ser.items()

In [62]:
list(ser.items())

[(0, 59), (1, 67), (2, 97), (3, 9), (4, 67), (5, 24), (6, 71)]

In [63]:
for index, value in ser.items():
    print(f"index: {index}, value : {value}")

index: 0, value : 59
index: 1, value : 67
index: 2, value : 97
index: 3, value : 9
index: 4, value : 67
index: 5, value : 24
index: 6, value : 71


In [65]:
[i for i in "cbaefdgihj"]

['c', 'b', 'a', 'e', 'f', 'd', 'g', 'i', 'h', 'j']

In [64]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

c     1
b    20
a    11
e    15
f     4
d    22
g     7
i    13
h    15
j     2
dtype: int32

In [67]:
ser.head()

c     1
b    20
a    11
e    15
f     4
dtype: int32

In [68]:
ser.tail()

d    22
g     7
i    13
h    15
j     2
dtype: int32

In [71]:
ser.sample(3) # datamızda herhangi bir yerden örneklem getirir.

c     1
h    15
b    20
dtype: int32

In [73]:
ser.sort_index(ascending=True) # defult True yazılarak sıralandı.

a    11
b    20
c     1
d    22
e    15
f     4
g     7
h    15
i    13
j     2
dtype: int32

In [75]:
ser.sort_values(ascending=False) # value göre sırlama yaptı.

d    22
b    20
e    15
h    15
i    13
a    11
g     7
f     4
j     2
c     1
dtype: int32

In [76]:
ser

c     1
b    20
a    11
e    15
f     4
d    22
g     7
i    13
h    15
j     2
dtype: int32

In [81]:
ser.isin([4,15]) # hangi değerlerim 4 ve 15 la çakışıyor.

c    False
b    False
a    False
e     True
f     True
d    False
g    False
i    False
h     True
j    False
dtype: bool

In [82]:
pd.Series([i for i in "Clarusway"])

0    C
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [83]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [84]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [85]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [86]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [87]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [90]:
ser1[1]

2

In [91]:
ser1["Germany"]

2

In [94]:
ser1.Germany # str  bir ifade ise yazılır. int olursa olmaz str de boşluk olmayacak.

2

Operations are then also done based off of index:

In [96]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [97]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [98]:
ser3[0]

'a'

In [99]:
ser3[:2]

0    a
1    b
dtype: object

In [100]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [101]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [104]:
panser[["terry", "orion"]] # ayrı ayrı satırı çağırmak için iki köşeli prantez olması lazım.

terry    121
orion    150
dtype: int64

In [103]:
panser["terry" : "orion"]

terry      121
micheal    200
orion      150
dtype: int64

In [105]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes and Some New Attributes

In [107]:
panser.keys() # str index varsa böyle yazar. int olursa star stop lu yazar

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [108]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [109]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [112]:
panser.item

<bound method IndexOpsMixin.item of terry      121
micheal    200
orion      150
jason       99
dtype: int64>

In [113]:
panser.items() # bunu for döngüsü ile ulaşıyoruz

In [111]:
for index, value in panser.items():
    print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [116]:
"terry" in panser # içerinde terry  varmı.

True

In [118]:
"bob" in panser

False

In [122]:
200 in panser.values # değer sorgulayacaksak .values içerinde sorgu yazmamız lazım

True

In [125]:
panser.isin([200,150]) #içerinde 200 , 150 varmı

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [127]:
panser["terry"] = 90
panser

terry       90
micheal    200
orion      150
jason       99
terrt       90
dtype: int64

In [129]:
panser[panser>100] = 175
panser

terry       90
micheal    175
orion      175
jason       99
terrt       90
dtype: int64